[package]
authors = ["{{authors}}"]
edition = "2018"
readme = "README.md"
name = "{{project-name}}"
version = "0.1.0"

[dependencies]
panic-halt = "0.2"
microbit="0.12.0"
cortex-m-rt="0.7.0"
rtt-target = { version = "0.3.1", features = ["cortex-m"] }

[build-dependencies]
cc = "1.0"
